{
 "title": "Cruze",
 "time": { "from": "2020-04-18T17:38:51.141Z", "to": "2020-04-18T17:41:24.572Z" },
 "panels": [
  {
   "title": "Track Car",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "latitude" ], "type": "tag" },
      { "params": [ "longitude" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "gps",
     "query": "SELECT mean(\"value\") AS \"metric\" FROM \"gps\" WHERE $timeFilter GROUP BY time($__interval), \"latitude\", \"longitude\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water Temp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "coolant_temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Location",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "latitude" ], "type": "tag" },
      { "params": [ "longitude" ], "type": "tag" }
     ],
     "measurement": "gps",
     "query": "SELECT latitude, longitude, last(\"value\") AS \"metric\" FROM \"gps\" WHERE $timeFilter order by time limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speed Historic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "velocitykmh" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "speed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Histrory Routes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "started_at" ], "type": "tag" }
     ],
     "measurement": "speed",
     "query": "SELECT last(\"value\"), time as Ended_at FROM \"speed\"  GROUP BY \"started_at\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Revolutions Historic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "rpm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "coolant_temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Live Speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speed",
     "query": "SELECT value FROM speed ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Revolutions",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rpm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}